### ISSUE TITLE
code...

### ISSUE THREAD

**Issue by Alexey-T** [thomasthorsen/SublimeProcapy#2]
```
def calc(n, expression, radix):
    try:
        result = eval(expression)
        if radix == "hex":
            result = hex(int(result))
        if radix == "binary":
            result = bin(int(result))
        if radix == "octal":
            result = oct(int(result))
        return str(result)
    except:
        return sys.exc_info()[0].__name__ + ": " + str(sys.exc_info()[1])
```

- use "elif" in func
- "n" not used totally- why its here

**Comment by thomasthorsen** [comment]
The variable n is made available to use inside the eval which calculates the expression from the selection. If you use "n" in an expression it will evaluate to the index of the selection. I.e. if you have multiple selections and trigger the calculation it will evaluate each selection separately. If that expression contains n, then n will be 0 in the first selection, 1 in the second selection, and so on.

Yes, it could have used elif, but it has no practical significance
